---
- name: Apache server installed
  hosts: webservers
  become: yes
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    systemd:
      name: httpd
      enabled: true
      state: started   
  - name: Deploy index.html
    copy:
      src: files/index.html
      dest: /var/www/html/index.html
