---
- name: webservers reconfigured
  hosts: webservers
  become: yes
  tasks:
  - name: httpd.conf copied on webservers
    copy:
      src: files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
  - name: restart httpd
    systemd:
      name: httpd
      state: restarted
