---
- name: MySQL server installation
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Install latest MySQL server when host RAM greater than 900 MB
    package:
      name: mysql-server
      state: latest
    when: ansible_memtotal_mb > 900
